Thu Jun  1 13:59:11 UTC 2023
GAg: 
Test passed, 1000 out of 1000 assertions passed

GAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 287 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
GAs: 
Test passed, 1000 out of 1000 assertions passed

PAg: 
Test passed, 1000 out of 1000 assertions passed

PAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 260 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at hardwar.branch.prediction.shared.devices.CombinationalLogic.hash(CombinationalLogic.java:99)
	at hardwar.branch.prediction.shared.devices.CombinationalLogic.hash(CombinationalLogic.java:82)
	at hardwar.branch.prediction.judged.PAs.PAs.predict(PAs.java:49)
	at hardwar.branch.prediction.judge.PredictorSimulator.lambda$simulate$0(PredictorSimulator.java:27)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at hardwar.branch.prediction.judge.PredictorSimulator.simulate(PredictorSimulator.java:30)
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:32)
SAg: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 114 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
SAp: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 342 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
SAs: 
Exception in thread "main" hardwar.branch.prediction.judge.TestFailedException: Test failed, 257 out of 1000 assertions passed
	at hardwar.branch.prediction.judge.Judge.main(Judge.java:39)
